stages:
  - build
  - deploy_personnal
  - deploy
build:
  stage: build
  image: alpine
  before_script:
    - apk add tar
  script:
   - mv src komposant
   - tar cvf source.tar komposant
  artifacts:
    paths:
      - source.tar

deploy_to_branches:
  stage: deploy
  image: alpine
  rules:
    - if: $CI_BRANCH_NAME != "master"
  environment:
    name: $CI_COMMIT_BRANCH
    url: https://dwarves.iut-fbleau.fr/~foucher/k_$CI_COMMIT_BRANCH/
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
  - scp -o StrictHostKeyChecking=no source.tar foucher@gatekeeper.iut-fbleau.fr:/export/home/an21/foucher/public_html/
  - ssh -o StrictHostKeyChecking=no foucher@gatekeeper.iut-fbleau.fr "cd public_html/;rm -rf k_$CI_COMMIT_BRANCH; tar xfv source.tar;rm source.tar;cp db_config.php k_$CI_COMMIT_BRANCH/includes/config.php"

deploy:
  stage: deploy
  image: alpine
  environment:
    name: prod
    url: https://dwarves.iut-fbleau.fr/~foucher/komposant/
  rules:
    - if: $CI_BRANCH_NAME == "master"
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
  - scp -o StrictHostKeyChecking=no source.tar foucher@gatekeeper.iut-fbleau.fr:/export/home/an21/foucher/public_html/
  - ssh -o StrictHostKeyChecking=no foucher@gatekeeper.iut-fbleau.fr "cd public_html/;rm -rf komposant; tar xfv source.tar;rm source.tar;cp db_config.php komposant/includes/config.php"